name: Release
on:
  push:
    tags:
      - "v**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/haskell-release-action@dcaef4fdd24e9eb1463e6ed448645c464bf263b0
        with:
          branch: main
          hackage-token: "nothing"
